# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71cdce2aa912c1a9ae3df15f75c1bb8fd66e1fecc8f303059ffd5934fcb8770aff36bfcf3bfcc66110a1333ef6585367c02e521812900fc5ce8836a8901c1bfc

test:
  secret_key_base: 38d7cb045cf3bd687f94b1a3ae3e6a7aaf6ae28696c04930fa1d1a01bec5309dec324122a10d29b43c03cdf3b81411b7fc1eceb4996e6e9eb80bacec31ed2356

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
